Repository AY2021S2-CS2103T-W15-4/tp, pull requests merged in 2021-03, with the labels that each got.

#42 40 implement back log&prog
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/BackLogCommand.java
  src/main/java/seedu/address/logic/commands/InProgressCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/BackLogCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/InProgressCommandParser.java
  src/main/java/seedu/address/model/event/EventStatus.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#45 44 implement basic front end [List View]
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/ui/EventCardListView.java
  src/main/java/seedu/address/ui/EventListPanelListView.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/EventCardListView.fxml
  src/main/resources/view/EventListPanelListView.fxml
Labels: priority.High

#54 50 - Redesign Event Card
  build.gradle
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/parser/BackLogCommandParser.java
  src/main/java/seedu/address/logic/parser/InProgressCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/TodoCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/EventPriority.java
  src/main/java/seedu/address/model/event/EventStatus.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/ui/EventCardKanbanView.java
  src/main/java/seedu/address/ui/EventListPaneKanbanView.java
  src/main/java/seedu/address/ui/KanbanPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/EventCardKanbanView.fxml
  src/main/resources/view/EventListPaneKanbanView.fxml
  src/main/resources/view/Extensions.css
  src/main/resources/view/KanbanPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/data/JsonSerializableEventBookTest/typicalEventsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/TodoCommandTest.java
  src/test/java/seedu/address/testutil/EventBuilder.java
Labels: priority.High

#72 70 implement find command
  docs/UserGuide.md
  docs/images/user-guide/find-after-execute.png
  docs/images/user-guide/find-before-execute.png
  docs/images/user-guide/list-example-1.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/event/EventContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.High, type.Story

#75 Add stream
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: priority.Medium, type.Enhancement

#77 59 refactor index to identifier
  src/main/java/seedu/address/commons/core/identifier/Identifier.java
  src/main/java/seedu/address/commons/core/identifier/Index.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/commons/core/identifier/IndexTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalIdentifiers.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.High
